travis:
  secure:
    BINSTAR_TOKEN: oJ1Imk90Cj6f6VAp0rfUEH/fl4rKn1H/IBrTwkdyine5+J564bFvYVNEx/2HRgYJ8xqqIuST1oqfdHFYXgCJKRmydcFssmpRjyu9LQMXmRxur0YvbkvMgF1PWpybfGoPR69rNHQTluF5YBiJlv+z7arH3YFoqOA2yewqLfOL+SsUQYOvfUO0MtYaTt7Qzr+AtForzsQRYMqBh+TV7sevK+1NBPpuHZ0NMdjVkK0wWjxOGvmPwoanxMTHKlt+ow1hiG5cEmcCi7M9zZfAe05PztEX8ubNe2LvdGmTm/oWSDVcdguxm4IFSpIHjsdsKMuQcNz1oeCmW5qwBBnPz5PJHTKWhHpYREBCdMmi8lKPRyYlTKYMSjtg8tYMnlCWddNBUqiX1eMPLj2Q8wEQJkdL9km0pG6en5AIvp8sMH1KxAcJ2uzj4sDHlQNVI4DyNqZJTBZKdgSAkoPxCa6nA+VtNPBnhvu7KDSWFL+6/JXJkzbuqZbSsfS164pw3noFQKImVMnFfFY7khF6zvtEYp5+tC/bd1ekvGohcKGIhjTtB+vrDBlmGAAZfC87KfPFqOTMc52LgTsNzdtZbUZFkfRkVA64L0qZjN9Rt297nVOHXkUtzlRuwYTJyin9MllEUSUd6syvaA4IvePx2R0thv6XXcO7YxOQNYKAneuU4jjWJ3w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
