travis:
  secure:
    BINSTAR_TOKEN: FAAiJS0w67JQtXWFFdv9I1RLEawuPNFGFqvoSlOavY59QPSDF1D4URkNwQv52MzgNTZQLpzzQvIka1VGjDdyWNHxEpsY7+YvxkNCPHyadJOlsbn6naaVlvt2eTaM0Kpk1Lef5OsR/LgsIRX4VRc9I3I70W0Ca8p5fVqLieoHhBgTYG6WaFKaY2mdDHm57dGh3vv4cDHIgrwqC2zU4ZSZpQ7JVH7ccjoPD5X3jh15lw/NbtbiYAKxlKpBzcsHkaIqtQEPWPnEVboZUf3NOdtW3jGzzuKrda5QuQobjxvLw+RspvMFw4WYMWtdbBKbN9jHe1qHZiprikTUX+C7MtMK7c6kehDtQX4BkZlsFku2XyE16vYAWXJJLspmQPF2qb3pvntLakrLqI0872ibbrdFxu+ZU1OpoWGWq8HC9BIXLyo87fU3YZcknawLtWLcjFrIC20BZFOAyRWMCaG6FVQ7cXGJ0elya/xMAop8AebvGJl1Oufho18F4js80ChaUlY1nszWzBiCXQ5uMQtWqTGSD5RqauU/pb2UOONNBd+usLfoIfZlLJd8WXqLSA/CD7lk3U8LDSYmuszm56KtoZUFO2DrnlYlHZdKo9AbYQkVlpIXFoQZvC5R6OJaG+qImKFoalwoNfptOkoFS6RwdmAO5/2kQMGK5f3QXLgmLeicyJc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
